### ISSUE TITLE
vue

### ISSUE THREAD

**Issue by wgjh5** [monoplasty/vue-monoplasty-slide-verify#1]
vue移动端划不动啊

**Comment by monoplasty** [comment]
没有设置touch事件，如可以PR

**Comment by monoplasty** [comment]
有时间再更新一下吧

**Comment by wgjh5** [comment]
PR是什么

**Comment by wgjh5** [comment]
我怎么改你的代码，才能在移动端滑动

**Comment by monoplasty** [comment]
不好意思，最近有点忙... 你需要先fork到你的仓库，然后你改好了在提交代码，发起一个pull requests ,然后我这边在合并分支就可以了.

**Comment by wgjh5** [comment]
我是说我不太会改，不知道怎么改

**Comment by monoplasty** [comment]
> 我是说我不太会改，不知道怎么改

已经发布新版本， 支持移动端touch事件
