### ISSUE TITLE
ie浏览器下终点滑块出不来如何解决？

### ISSUE THREAD

**Issue by heweijuan** [monoplasty/vue-monoplasty-slide-verify#10]

**Comment by heweijuan** [comment]
ctx.globalCompositeOperation = 'overlay' ie下好像没生效，换成ctx.globalCompositeOperation = 'source-out'，ie浏览器下终点滑块出来了。

**Comment by monoplasty** [comment]
> ctx.globalCompositeOperation = 'overlay' ie下好像没生效，换成ctx.globalCompositeOperation = 'source-out'，ie浏览器下终点滑块出来了。

针对IE， 我没有做很多的兼容性测试。 抱歉

**Comment by monoplasty** [comment]
已修复  [issue#26](https://github.com/monoplasty/vue-monoplasty-slide-verify/issues/26)
