### ISSUE TITLE
请问怎么做后端的回调数据校验, 现在这个组件是纯前端校验的嘛?

### ISSUE THREAD

**Issue by nagaame** [monoplasty/vue-monoplasty-slide-verify#16]

**Comment by monoplasty** [comment]
> _No description provided._



> _No description provided._

目前组件是校验滑动成功。
要校验后端数据的话需要在滑动成功之后的回调函数里进行判断验证了。 
暂时不知道你的登录逻辑，如有问题，可以继续交流学习！

**Comment by nagaame** [comment]
简单来说就是, 回调的时候, 应该把滑动轨迹数据提交到后端, 后端也计算一下这些轨迹方差, 没有问题才允许 通过验证, 现在我想问问success之后有没有相关的轨迹参数

因为登录的话, 后端的接口肯定需要一些滑动验证或者验证码的数据的

**Comment by monoplasty** [comment]
> 简单来说就是, 回调的时候, 应该把滑动轨迹数据提交到后端, 后端也计算一下这些轨迹方差, 没有问题才允许 通过验证, 现在我想问问success之后有没有相关的轨迹参数
> 
> 因为登录的话, 后端的接口肯定需要一些滑动验证或者验证码的数据的

我的理解是：不需要后端去验证轨迹数据。因为前端已经处理过了。可以再验证成功的回调里向后端请求一个随机验证码的数据，然后点击登录的时候在将这个数据传给后端

**Comment by nagaame** [comment]
好的, 谢谢解答😊
