### ISSUE TITLE
在父组件中设置不了imgs的属性

### ISSUE THREAD

**Issue by Lcwben** [monoplasty/vue-monoplasty-slide-verify#17]
想使用本地的图片作为滑动验证图片，在父组件中created生命周期设置this.$refs.slideblock.imgs = 图片的项目路径数组，发现没有生效，验证图片路径，发现路径没有错。请问作者，是我属性设置方式不正确？还是什么其他的原因造成？？
模板：
`<template>
    <slide-verify
      :l="42"
      :r="10"
      :w="310"
      :h="155"
      ref = "slideblock"
      slider-text="向右滑动"
      @mousedown.native="getMouseDownTime()"
      @mousemove.native="getMouseMoveTrail($event)"
      @mouseup.native="getMouseUpTime()"
      @success="onSuccess"
      @fail="onFail"
      @refresh="onRefresh"
    />
</template>`

代码：
`import { slideVerifyLogic } from '@/api/slideVerify'

export default {
  name: 'SlideVerifyTool',
  data() {
    return {
      query: {
        mouseDownTime: null,
        mouseDragTime: null,
        locationCount: 0,
        locationSum: 0,
        verifySuccess: false
      },
    }
  },
  created() {
    this.$refs.slideblock.imgs = ['@/assets/slide-verify-img/1.jpg', '@/assets/slide-verify-img/2.jpg', '@/assets/slide-verify-img/3.jpg']
  },
...`

**Comment by monoplasty** [comment]
只需要在组件上进行传参 imgs  就可以了。
具体可以参考  [App.vue 上的代码](https://github.com/monoplasty/vue-monoplasty-slide-verify/blob/master/src/App.vue)
比较推荐使用 cdn 或图床的链接地址。
如有疑问请留言。

**Comment by Lcwben** [comment]
> 只需要在组件上进行传参 imgs 就可以了。
> 具体可以参考 [App.vue 上的代码](https://github.com/monoplasty/vue-monoplasty-slide-verify/blob/master/src/App.vue)
> 比较推荐使用 cdn 或图床的链接地址。
> 如有疑问请留言。

**Comment by Lcwben** [comment]
原来是我自己的使用方式和理解错了，看了代码样例后已经解决了问题，谢谢作者。
