### ISSUE TITLE
imgs数组应该怎么写啊？

### ISSUE THREAD

**Issue by dongwa** [monoplasty/vue-monoplasty-slide-verify#19]
本地图片和网络url都必须使用import引入吗？为什么我按照app.vue里面的写法各种报错啊

**Comment by monoplasty** [comment]
> 本地图片和网络url都必须使用import引入吗？为什么我按照app.vue里面的写法各种报错啊

你好，感谢你的反馈。 

首先你可以看到我App.vue 文件里写的引入图片的方式是引用的本地的路径。 事实上，所需要传的imgs参数就是一个合法的img路径就行了 。 如果是cdn地址（网络地址）的话，直接放在imgs数组里就可以了。

如果你本地报错，你可以试着把报错信息等相关问题，在问题里稍微写详细一些。这样，我们看到了也方便帮你定位问题所在。

**Comment by dongwa** [comment]
感谢你的回复。我的问题已经解决啦。谢谢
