### ISSUE TITLE
拼图模式下，滑动出现卡顿现象。

### ISSUE THREAD

**Issue by Luckyseal** [monoplasty/vue-monoplasty-slide-verify#2]
拼图模式下，滑动出现卡顿现象。

**Comment by Luckyseal** [comment]
![_20190228205518](https://user-images.githubusercontent.com/8158542/53567835-5a273780-3b9b-11e9-80be-715564de29c2.jpg)
拼图和下部的 mask条，滑块的动作不同步。 抠出的图片不是带有边框

**Comment by monoplasty** [comment]
出现问题的频率高吗？
有可能的原因是图片请求的是公共服务器地址，出现请求延迟的问题
具体原因待排查

**Comment by monoplasty** [comment]
> 拼图模式下，滑动出现卡顿现象。

如果问题很严重， 那需要使用本地的图片文件了

**Comment by fengfumin** [comment]
兼容性不太好，某些浏览器滑块会出错

**Comment by monoplasty** [comment]
> 兼容性不太好，某些浏览器滑块会出错

如果您有兼容性的建议, 欢迎fork

**Comment by monoplasty** [comment]
换了本地的图片路径，应该可以解决这个问题
