### ISSUE TITLE
如果获取后台给的图片

### ISSUE THREAD

**Issue by chinajian** [monoplasty/vue-monoplasty-slide-verify#21]
您的前台效果做的非常棒，但是有个问题，目前只有前台效果，并没有在后台获取到什么内容，比如之前图形验证码，需要再后台获取图片，如果不在后台验证的话，机器很容绕过前台，直接请求接口，这样验证码就形同虚设了

**Comment by monoplasty** [comment]
> 您的前台效果做的非常棒，但是有个问题，目前只有前台效果，并没有在后台获取到什么内容，比如之前图形验证码，需要再后台获取图片，如果不在后台验证的话，机器很容绕过前台，直接请求接口，这样验证码就形同虚设了

您说的没错。 我想到的有两种方法可以尝试：
1.  每次验证之前让后台生成一串数字。 当用户滑动成功之后，将这串数字直接传给后台做校验。 
2. 修改源码部分。 让服务器生成 `this. block_x `数据，然后修改 `verify` 方法 要求服务器取验证数据。 

如果您有什么好的方法，可以共同探讨一下。感谢您的回复！

**Comment by cyn0t** [comment]
服务器生成 this. block_x 数据，如果传给前端，那自然就暴露了啊，如果不传给前端 背景在哪镂空也是个问题
起始后端可以很容易切割图片 和位置 然后传给前端
前端在把滑动的坐标结果给到后端 可能会好很多
但是我看源码是canvas画的 看能不能改成两个img
