### ISSUE TITLE
IE11-IE9显示有问题

### ISSUE THREAD

**Issue by MaJiaXuan** [monoplasty/vue-monoplasty-slide-verify#22]
IE11-IE9显示有问题

![image](https://user-images.githubusercontent.com/24503453/82770456-500dea80-9e6b-11ea-9394-9dc8118cb0f5.png)
![image](https://user-images.githubusercontent.com/24503453/82770586-a7ac5600-9e6b-11ea-8919-7c7a3f24272e.png)

**Comment by MaJiaXuan** [comment]
IE9滑动不了

**Comment by monoplasty** [comment]
> IE9滑动不了

新版本V1.1.3 已修复。
