### ISSUE TITLE
图片显示不出来

### ISSUE THREAD

**Issue by sailyw** [monoplasty/vue-monoplasty-slide-verify#23]
您好，图片需要加载很久才出来，是服务器出了什么问题吗？

**Comment by monoplasty** [comment]
> 您好，图片需要加载很久才出来，是服务器出了什么问题吗？

目前用的图片地址是一个公共api， 建议你使用自定义的图片地址

**Comment by wenxiayili** [comment]
> > 您好，图片需要加载很久才出来，是服务器出了什么问题吗？
> 
> 目前用的图片地址是一个公共api， 建议你使用自定义的图片地址

如何修改图片的地址呢？

**Comment by monoplasty** [comment]
> > > 您好，图片需要加载很久才出来，是服务器出了什么问题吗？
> > 
> > 
> > 目前用的图片地址是一个公共api， 建议你使用自定义的图片地址
> 
> 如何修改图片的地址呢？

可以参考文档中的demo . 已更新新版本
