### ISSUE TITLE
膜拜大佬，能否做一个可以获取用户从开始拖动到成功的时间累计，比如你只用了1.3S，真棒

### ISSUE THREAD

**Issue by 157085905lh** [monoplasty/vue-monoplasty-slide-verify#24]

**Comment by monoplasty** [comment]
感谢你的建议。 可以考虑试试。 目前工作有点忙， 之后可以修改一下。 有好的想法可以提一下PR，感谢你的关注

**Comment by monoplasty** [comment]
已发新版V1.1.3。 在成功回调中返回 时间参数。单位毫秒。 其余的文案自己可以判断。 比如 1-3秒之内，提示真棒，3-5秒内，提示手速不行 等等。 😝
