### ISSUE TITLE
ie9-ie11有问题

### ISSUE THREAD

**Issue by a2541531647** [monoplasty/vue-monoplasty-slide-verify#26]
图片上的白色拼图显示不出

**Comment by Guosugaz** [comment]
改源码，组件methods.draw函数，最后执行的ctx.globalCompositeOperation = "overlay"; 改为 ctx.globalCompositeOperation = "destination-over";，同时解决了火狐裁剪滑块不完全的问题

**Comment by a2541531647** [comment]
> 改原始码，组件methods.draw函数，最后执行的ctx.globalCompositeOperation =“ overlay”; 替换ctx.globalCompositeOperation =“ destination-over” ;，同时解决了火狐裁剪滑块不完全的问题

感谢大佬 问题以解决 谢谢谢谢

**Comment by monoplasty** [comment]
合并 @Guosugaz 代码，测试了IE9-11，见下图。其余功能见文档
![image](https://user-images.githubusercontent.com/25847735/85968525-ecda1f80-b9f7-11ea-873b-bb6ef73fef80.png)
![image](https://user-images.githubusercontent.com/25847735/85968549-f8c5e180-b9f7-11ea-8bae-1849132d90bc.png)
![image](https://user-images.githubusercontent.com/25847735/85968563-04190d00-b9f8-11ea-9bc7-ea3c4a4e42ee.png)
