### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by xiangzi1** [monoplasty/vue-monoplasty-slide-verify#3]
比如我的图片验证码与登录配合使用时，调用后台接口失败后，不点击刷新按钮，不能重新加载刷新验证码

**Comment by monoplasty** [comment]
组件有一个reset方法，后台接口失败后，可以手动调用 子组件的reset方法进行重置。
`<slide-verify ref="slideblock" @success="onSuccess" @fail="onFail" @refresh="onRefresh" :slider-text="text"></slide-verify>`
// js
`onSuccess(){
      this.msg = 'login success';
      setTimeout(() => {
         this.$refs.slideblock.reset();
      }, 500);
  },`
