### ISSUE TITLE
没有暴露一个可以手动触发刷新图片（不使用点击刷新图标触发）的方法吗文档里面找不到呢

### ISSUE THREAD

**Issue by hanxiaosss** [monoplasty/vue-monoplasty-slide-verify#4]

**Comment by monoplasty** [comment]
嗯. 方法是有的. 拿到组件实例. 
```html
<slide-verify ref="slideblock" @success="onSuccess" @fail="onFail" @refresh="onRefresh" :slider-text="text"></slide-verify>
```
```javascript
this.$refs.slideblock.reset();
```
在父组件中调用子组件`reset()` 方法就可以了

**Comment by zyanqing123** [comment]
苹果刷新后图片没出来怎么解决

**Comment by monoplasty** [comment]
> 苹果刷新后图片没出来怎么解决

因为这个图片链接是采用的是这个网站的api `https://picsum.photos/` 所以可能的原因的网络问题

**Comment by hanxiaosss** [comment]
> 嗯. 方法是有的. 拿到组件实例.
> 
> ```
> <slide-verify ref="slideblock" @success="onSuccess" @fail="onFail" @refresh="onRefresh" :slider-text="text"></slide-verify>
> ```
> 
> ```js
> this.$refs.slideblock.reset();
> ```
> 
> 在父组件中调用子组件`reset()` 方法就可以了

谢谢，现在确实这么解决的
