### ISSUE TITLE
部分手机浏览器，滑块无法滑动。

### ISSUE THREAD

**Issue by Junesui** [monoplasty/vue-monoplasty-slide-verify#49]
手机谷歌浏览器没问题。目前小米浏览器，360浏览器等等，滑块无法滑动。只能向前滑动一丢丢

**Comment by monoplasty** [comment]
尝试更改源码，组件methods.draw函数，最后执行的ctx.globalCompositeOperation = "overlay"; 改为 ctx.globalCompositeOperation = "destination-over";，。
移动端没有调试过，需要尝试看看能不能解决问题。
