### ISSUE TITLE
ts版本

### ISSUE THREAD

**Issue by kuangshp** [monoplasty/vue-monoplasty-slide-verify#5]
建议提供下ts的声明文件的，及开放源码

**Comment by monoplasty** [comment]
感谢你的建议。只是目前我对ts不大了解。 没有具体实践过。至于源码不是已经开放到github上了吗？ 如果你感兴趣不知能不能请你为这个项目写一份声明文件。 可以PR。

**Comment by kuangshp** [comment]
> 感谢你的建议。只是目前我对ts不大了解。 没有具体实践过。至于源码不是已经开放到github上了吗？ 如果你感兴趣不知能不能请你为这个项目写一份声明文件。 可以PR。

过一阵子我有时间来帮你写申明文件

**Comment by JerryWang24** [comment]
> > 感谢你的建议。只是目前我对ts不大了解。 没有具体实践过。至于源码不是已经开放到github上了吗？ 如果你感兴趣不知能不能请你为这个项目写一份声明文件。 可以PR。
> 
> 过一阵子我有时间来帮你写申明文件

你这一阵子好像有点儿久~~在线等
