### ISSUE TITLE
微信H5使用时，当手机字体设置为“关怀模式”或字体调到最大时，滑动验证出现明显卡顿

### ISSUE THREAD

**Issue by xiqiuqiu** [monoplasty/vue-monoplasty-slide-verify#58]
#### 环境：
微信8.024 
#### 问题：
拖动滑块时发现明显卡顿
#### 验证：
经过测试发现，当微信内文字大小变化时，会出现明显卡顿；反之就可以正常运行；

迫于研究了很久没有发现结果，想请问下作者，这两者是如何相互作用的？

**Comment by xiqiuqiu** [comment]
今天又测试了，最后发现问题还不是 微信字体大小导致的卡顿；而是滑动组件如果有外部元素包裹就会导致组件出现拖动卡顿的情况。
比方说：用`<div><slide-verify></slide-verify></div>`类似形式去包装组件，就大概率会出现多次的拖动卡顿的情况。
反正现在也不知道为什么，迫于技术菜，只是一点点去做排除法。

**Comment by monoplasty** [comment]
我自己在移动端试了一下，想到了一种可能： 在移动端的话，需要对拖拽事件进行防抖。可以朝这个方式试试。

**Comment by monoplasty** [comment]
> 今天又测试了，最后发现问题还不是 微信字体大小导致的卡顿；而是滑动组件如果有外部元素包裹就会导致组件出现拖动卡顿的情况。 比方说：用`<div><slide-verify></slide-verify></div>`类似形式去包装组件，就大概率会出现多次的拖动卡顿的情况。 反正现在也不知道为什么，迫于技术菜，只是一点点去做排除法。

我提交了一个版本V1.1.5。在原来基础上增加了事件节流。 移动端测试不怎么卡顿了。你更新看看。

**Comment by xiqiuqiu** [comment]
测试了，卡顿的情况确实好很多了。感谢

**Comment by monoplasty** [comment]
> 测试了，卡顿的情况确实好很多了。感谢

好的， 谢谢你共建开源项目，有什么问题以后也可多多交流
