### ISSUE TITLE
设置画布宽度后下方的滑块区域不会跟随改变长度

### ISSUE THREAD

**Issue by chuyinghua** [monoplasty/vue-monoplasty-slide-verify#6]
设置画布宽度（ w ）后下方的滑块区域不会跟随改变长度 造成画布和下方的拖动区长度不一致

**Comment by monoplasty** [comment]
虽然不是很明白你的需求， 但是我大致也知道，你应该是觉得尺寸有点不协调。 这个没有特别去设计。 只是作了一个例子。具体还需要设计一下才行。 可以请你给一个参考吗？
