### ISSUE TITLE
你好  跨域

### ISSUE THREAD

**Issue by lcy-132056117** [monoplasty/vue-monoplasty-slide-verify#60]
2022年9月7日12:07:55
项目使用该插件报跨域 不知道为啥?
![image](https://user-images.githubusercontent.com/52149924/188786734-b404a936-6b74-4d0d-88ff-f96e4faa05f0.png)

**Comment by monoplasty** [comment]
你好，组件中使用了第三方的随机图片api， 该获取到的图片现已无法免费使用。 现已更换一个新的图片源（已更新到版本v1.3.1，更新即可）。 但无法保证该图片源能长期维护使用。强烈建议使用 自己的cdn链接来保证图片资源的可用性！！

**Comment by lcy-132056117** [comment]
> 

好的  谢谢

**Comment by lcy-132056117** [comment]
你好 我现在项目中用的就是1.3.0版本的vue-monoplasty-slide-verify   昨天都没有问题  但是今天才报跨域 加载不出来的   我这边需要怎么操作 就可以正常使用了呢?
