### ISSUE TITLE
经常会出现获取不到图片的问题

### ISSUE THREAD

**Issue by HasGenvts** [monoplasty/vue-monoplasty-slide-verify#62]
经常会出现获取不到图片的问题

**Comment by monoplasty** [comment]
推荐使用本地图片，或者自己oss 或cdn上的图片。 目前使用的第三方图片api 不是很稳定。

> 经常会出现获取不到图片的问题

**Comment by ZYQMESSi** [comment]
vue3可以用吗

**Comment by HasGenvts** [comment]
我已经收到邮件了，我将会在稍后进行回复。I have received the email, I will reply later.

**Comment by HasGenvts** [comment]
vue3应该有一个专门的版本吧

**Comment by monoplasty** [comment]
> vue3可以用吗

vue3 地址： https://github.com/monoplasty/vue3-slide-verify
