### ISSUE TITLE
请问图片验证码有的时候超慢怎么解决？

### ISSUE THREAD

**Issue by chjish28461** [monoplasty/vue-monoplasty-slide-verify#8]
建议内置10几张图片随机出现就不会了

**Comment by monoplasty** [comment]
ok 最近忙的没时间编码。 等空一些了把图片列表开放出来。 要是你愿意可以拉一下代码了。 实现你的功能。 共同改进这个功能。感谢大家！

**Comment by monoplasty** [comment]
V1.1.0 版本已经解决，可以传 `imgs` 图片数组。具体可以看App.vue 的例子和在线demo
